apiVersion: v1
kind: Service
metadata:
  name: healthcare-api-svc
  labels:
    app: healthcare-api
spec:
  type: ClusterIP
  selector:
    app: healthcare-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
